const crypto = require("node:crypto");

const BLOCK_START = "# >>> grok-desktop custom models >>>";
const BLOCK_END = "# <<< grok-desktop custom models <<<";

function cleanBaseUrl(input) {
  const value = String(input || "").trim();
  const parsed = new URL(value);
  if (!/^https?:$/.test(parsed.protocol)) throw new Error("URL 需要使用 http 或 https 协议");
  parsed.hash = "";
  parsed.search = "";
  return parsed.toString().replace(/\/+$/, "");
}

function endpointCandidates(input) {
  const url = cleanBaseUrl(input);
  if (/\/models$/i.test(url)) return [{ listUrl: url, baseUrl: url.replace(/\/models$/i, "") }];
  if (/\/v1$/i.test(url)) return [{ listUrl: `${url}/models`, baseUrl: url }];
  return [
    { listUrl: `${url}/models`, baseUrl: url },
    { listUrl: `${url}/v1/models`, baseUrl: `${url}/v1` }
  ];
}

function protocolOrder(url, key) {
  const hint = `${url} ${key}`.toLowerCase();
  return hint.includes("anthropic") || hint.includes("claude") || hint.includes("sk-ant")
    ? ["anthropic", "openai"]
    : ["openai", "anthropic"];
}

function headersFor(protocol, key) {
  if (protocol === "anthropic") {
    return { "x-api-key": key, "anthropic-version": "2023-06-01", accept: "application/json" };
  }
  return { authorization: `Bearer ${key}`, accept: "application/json" };
}

function parseModels(body, protocol) {
  const data = Array.isArray(body?.data) ? body.data : Array.isArray(body?.models) ? body.models : null;
  if (!data) throw new Error("响应中没有模型列表");
  return data
    .map((item) => typeof item === "string" ? { id: item } : item)
    .filter((item) => typeof item?.id === "string" && item.id.trim())
    .map((item) => ({
      id: item.id.trim(),
      name: item.display_name || item.name || item.id.trim(),
      owner: item.owned_by || (protocol === "anthropic" ? "anthropic" : "provider"),
      created: item.created_at || item.created || null,
      contextWindow: Number(item.max_input_tokens) > 0 ? Number(item.max_input_tokens) : null,
      maxOutput: Number(item.max_tokens) > 0 ? Number(item.max_tokens) : null
    }));
}

async function discoverModels({ baseUrl, apiKey }, fetchImpl = globalThis.fetch) {
  const url = cleanBaseUrl(baseUrl);
  const key = String(apiKey || "").trim();
  if (!key) throw new Error("请填写 API 密钥");
  const attempts = [];
  for (const protocol of protocolOrder(url, key)) {
    for (const endpoint of endpointCandidates(url)) {
      try {
        const response = await fetchImpl(endpoint.listUrl, {
          method: "GET",
          headers: headersFor(protocol, key),
          signal: AbortSignal.timeout(12_000)
        });
        if (!response.ok) {
          const detail = (await response.text()).slice(0, 220).replace(/\s+/g, " ");
          attempts.push(`${protocol} ${response.status}${detail ? `: ${detail}` : ""}`);
          continue;
        }
        const body = await response.json();
        const models = parseModels(body, protocol);
        if (!models.length) {
          attempts.push(`${protocol}: 返回了空模型列表`);
          continue;
        }
        return { protocol, baseUrl: endpoint.baseUrl, listUrl: endpoint.listUrl, models };
      } catch (error) {
        attempts.push(`${protocol}: ${error.message}`);
      }
    }
  }
  throw new Error(`模型发现失败。${attempts.slice(-3).join("；")}`);
}

function slug(value, fallback = "model") {
  const result = String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 56);
  return result || fallback;
}

function makeProviderId(baseUrl) {
  return `provider-${crypto.createHash("sha256").update(cleanBaseUrl(baseUrl)).digest("hex").slice(0, 10)}`;
}

function makeEnvKey(providerId) {
  return `GROK_DESKTOP_KEY_${providerId.replace(/[^A-Za-z0-9]/g, "_").toUpperCase()}`;
}

function makeLocalModelId(providerId, remoteId) {
  return `desktop-${slug(providerId.replace(/^provider-/, "provider"), "provider")}-${slug(remoteId)}`.slice(0, 110);
}

function tomlString(value) {
  return JSON.stringify(String(value));
}

function renderManagedConfig(providers) {
  const lines = [BLOCK_START, "# Generated by Grok Build Desktop. Edit providers in Desktop Settings."];
  for (const provider of providers) {
    for (const model of provider.models || []) {
      lines.push(
        "",
        `[model.${tomlString(model.localId)}]`,
        `model = ${tomlString(model.id)}`,
        `base_url = ${tomlString(provider.baseUrl)}`,
        `name = ${tomlString(model.name || model.id)}`,
        `description = ${tomlString(`${provider.protocol === "anthropic" ? "Anthropic" : "OpenAI"} · ${provider.baseUrl}`)}`,
        `env_key = ${tomlString(provider.envKey)}`,
        `api_backend = ${tomlString(provider.protocol === "anthropic" ? "messages" : "chat_completions")}`,
        `context_window = ${Math.max(1, Number(model.contextWindow) || 200000)}`,
        "supported_in_api = true"
      );
      if (provider.protocol === "anthropic") {
        lines.push('auth_scheme = "x_api_key"', 'extra_headers = { "anthropic-version" = "2023-06-01" }');
      }
      if (Number(model.maxOutput) > 0) lines.push(`max_completion_tokens = ${Math.round(Number(model.maxOutput))}`);
    }
  }
  lines.push(BLOCK_END);
  return lines.join("\n");
}

function mergeManagedConfig(existing, providers) {
  const escapedStart = BLOCK_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const escapedEnd = BLOCK_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(`\\n?${escapedStart}[\\s\\S]*?${escapedEnd}\\n?`, "g");
  const clean = String(existing || "").replace(pattern, "\n").trimEnd();
  const generated = renderManagedConfig(providers);
  return `${clean}${clean ? "\n\n" : ""}${generated}\n`;
}

module.exports = {
  BLOCK_START,
  BLOCK_END,
  cleanBaseUrl,
  discoverModels,
  endpointCandidates,
  makeProviderId,
  makeEnvKey,
  makeLocalModelId,
  mergeManagedConfig,
  parseModels,
  renderManagedConfig
};
